# Use the official Node.js image as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Expose the port your Next.js app will run on (usually 3000)
EXPOSE 3000

# Start your Next.js app
CMD ["npm", "run", "start"]
