version: "3"
services:
  nextjs:
    build: ./
    container_name: well_pharmacy
    image: a7medabdo6/well_pharmacy
      ports:
        - 3000:3000
  
  watchtower:
    image: containrrr/watchtower
    restart: always
    environment:
      # WATCHTOWER_SCHEDULE: "0 0 1 * * *"
      TZ: America/Chicago
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 well_pharmacy well_pharmacy
